scenario('Check the existence of the voucher code generated by "Google adwords" module', () => {
    scenario('Login in Back Office', client => {
        test('should open the browser', () => client.open());
        test('should login successfully in BO', () => client.signInBO());
    }, "gadwords_client");
    scenario('Check the voucher code in the configuration page', client => {
        test('should go to "Installed modules" page', () => client.goToModulesPage());
        test('should search "gadwords" module', () => client.searchModule('gadwords'));
        test('should check that "gadwords" module is installed', () => client.getInstalledModulesNumber());
        test('should get the name of the first action button of the module', () => client.getModuleButtonName());
        test('should click on "Configure" button', () => client.clickConfigureModuleButton('gadwords'));
        test('should check that "Google AdWords" promotional code appears in the configuration page', () => client.checkGoogleAdwordsPromotionalCode());
        test('should click on "Start your campaign now with your promotional code" button', () => client.clickStartButton());
        test('should check that "Google Adwords" voucher appears in the page', () => client.checkGoogleAdwordsVoucher());
    }, "gadwords_client");
    scenario('Logout from the Back Office', client => {
        test('should logout successfully from the Back Office', () => client.signOutBO());
    }, "gadwords_client");
}, "gadwords_client", true);